version: "3.8"
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    networks:
      - main

  # dev-web:
  #   build:
  #     context: ./app
  #     dockerfile: ./docker/Dockerfile
  #   env_file:
  #     - ./app/.env
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:admin@dev-db:5432/postgres
  #   volumes:
  #     - ./app:/app
  #     - /app/node_modules
  #     - /app/.next
  #   # ports:
  #   #   - 3000:3000
  #   depends_on:
  #     - dev-db
  #   networks:
  #     - main
  #   entrypoint: ["/bin/sh", "/app/docker/entrypoint.sh"]

networks:
  main:
