version: "3.8"
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    networks:
      - main
  dev-scheduler:
    build:
      context: .
      dockerfile: ./docker/scheduler/Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URI=postgresql://postgres:admin@dev-db:5432/postgres
    networks:
      - main
    # volumes:
    #   - .:/app
    depends_on:
      - dev-db
    entrypoint: ["/bin/sh", "/app/entrypoint.sh"]

networks:
  main:
